server: 
  port: 9004
spring:
  cloud:
    refresh:
      refreshable: none
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://13.66.200.214:3306/tensquare_article?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 13.66.200.214
  data:
    mongodb:
      host: 13.66.200.214
      database: recruitdb
  rabbitmq:
    host: 13.66.200.214
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://13.66.200.214:6868/eureka/
  instance:
    prefer-ip-address: true
