server:
  port: 9001
spring:
  cloud:
    refresh:
      refreshable: none
  application:
    name: tensquare-base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://52.183.23.78:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 52.183.23.78
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://52.183.23.78:6868/eureka/
  instance:
    prefer-ip-address: true
sms:
  ip: 127.0.0.111
