server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.2.15:3306/tensquare_gathering?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 10.0.2.15
