server: 
  port: 9003
spring:
  cloud:
    refresh:
      refreshable: none
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.2.15:3306/tensquare_qa?characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 10.0.2.15
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://10.0.2.15:6868/eureka/
  instance:
    prefer‐ip‐address: true
feign:
  hystrix:
    enabled: true
