server:
  port: 9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 13.66.200.214:9300
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://13.66.200.214:6868/eureka/
  instance:
    prefer‐ip‐address: true
