server:
  port: 9007
spring:
  cloud:
    refresh:
      refreshable: none
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 10.0.2.15:9300
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://10.0.2.15:6868/eureka/
  instance:
    prefer‐ip‐address: true
