server:
  port: 9009
spring:
  cloud:
    refresh:
      refreshable: none
  application:
    name: tensquare-sms
  rabbitmq:
    host: 10.0.2.15
aliyun:
  sms:
    accessKeyId: LTAIxo9ZQy1tSHYL
    accessKeySecret: IawJXWPqlMvG69lzCcEOBoyvGvwE5G
    template_code: SMS_94700095
    sign_name: 李腾飞自己做短信测试
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://10.0.2.15:6868/eureka/
  instance:
    prefer-ip-address: true
