server:
  port: 9006
spring:
  cloud:
    refresh:
      refreshable: none
  application:
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 10.0.2.15
      database: spitdb
  redis:
    host: 10.0.2.15
  rabbitmq:
    host: 10.0.2.15
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://10.0.2.15:6868/eureka/
  instance:
    prefer-ip-address: true


