server:
  port: 9006
spring:
  cloud:
    refresh:
      refreshable: none
  application:
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 13.66.200.214
      database: spitdb
  redis:
    host: 13.66.200.214
  rabbitmq:
    host: 13.66.200.214
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://13.66.200.214:6868/eureka/
  instance:
    prefer-ip-address: true


